### ISSUE TITLE
Corrupted Skynest color AOE debuff

### ISSUE THREAD

**Issue by Leonellar** [pepsimemen/Corrupted-Skynest-Forbidden-Arena#1]
Hi. The color debuff doesn't seem to work correctly most of the time after the update in our server after maintenance. When it says innerfireIN when you go IN, you still die and vice versa. Is there an update about this? Thank you!

**Comment by pepsimemen** [comment]
use shindmitry mod instead is better
https://github.com/hsdn/tera-guide
